apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name:  db
  labels:
    name:  db
spec:
  template:
    metadata:
      labels:
        name:  db
    spec:
      containers:
      - image:  mongo
        name:  mongodb
        resources:
          requests:
            cpu: "20m"
            memory: "55M"
          limits:
            cpu: "128M"
            memory: "200m"
        env:
          - name:  MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongodb_secret
                key:  MONGO_INITDB_ROOT_USERNAME 
          - name:  MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name:  mongodb_secret
                key: MONGO_INITDB_ROOT_PASSWORD
        ports:
        - containerPort:  27017
      restartPolicy: Always
      imagePullPolicy: Always