pipeline{
    agent any

      environment {
        DOCKER_REGISTRY = 'docker.io'           // Replace with your Docker registry
        DOCKER_REPO = 'ahmed5555555555/simple-app' // Replace with your Docker repository
        IMAGE_TAG = 'latest'                    // Replace with the tag you want to use
        DOCKER_CREDENTIALS_ID = 'dockerhub' // Replace with the Jenkins credentials ID
    }
    

    stages{
        stage('Build Docker Image') {
            steps {
                script {
                    // Build Docker image from the Dockerfile in the repository
                    dockerImage = docker.build("${DOCKER_REPO}:${IMAGE_TAG}")
                }
            }
        }
    }
    post{
        always{
            echo "========always========"
        }
        success{
            echo "========pipeline executed successfully ========"
        }
        failure{
            echo "========pipeline execution failed========"
        }
    }
}